# Generated by Django 4.1.1 on 2022-09-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=100)),
                ('AUTHOR', models.CharField(max_length=12)),
                ('PUBLISHER', models.CharField(max_length=12)),
            ],
        ),
    ]
